use_frameworks!

target 'iosutilities_Example' do
    
    inhibit_all_warnings!
    
    pod 'PKHUD'
    pod 'AlamofireObjectMapper'
    pod 'Alamofire'
    pod 'ActionSheetPicker-3.0'
    pod 'RealmSwift'
    pod 'CryptoSwift'
    
  pod 'iosutilities', :path => '../'

  target 'iosutilities_Tests' do
    inherit! :search_paths

    
  end
end
