use_frameworks!

target 'iosutilities_Example' do
    
    inhibit_all_warnings!
    
    pod 'PKHUD', '~> 4.0'
    pod 'AlamofireObjectMapper', '~> 5.0'
    pod 'Alamofire', '~> 4.5'
    pod 'ActionSheetPicker-3.0'
    pod 'RealmSwift'
    
  pod 'iosutilities', :path => '../'

  target 'iosutilities_Tests' do
    inherit! :search_paths

    
  end
end
